# Vypíš URI a názov všetkých vedľajších účinkov zlúčeniny DB00679. 

# definujeme predpony
PREFIX het: <https://het.io/>               
PREFIX drug: <https://bioregistry.io/drugbank:>   
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>  

# Dopyt
SELECT 
    ?compound             # vyberame URI zluceniny
    ?compound_label       # nazov zluceniny
    ?side_effect          # URI vedlasieho ucinku zluceniny
    ?side_effect_label    # nazov vedlajsieho ucinku
WHERE {
    # definicia zlucenina na ktoru sa dopytujeme
    BIND(drug:DB00679 AS ?compound)
    
    ?compound het:causes ?side_effect .  # vedlajsi ucinok, ktory zlucenina sposobuje
    ?compound skos:prefLabel ?compound_label .  # ziskame nazov zluceniny
    ?side_effect skos:prefLabel ?side_effect_label .  # ziskame nazov vedlajsieho ucinku
}
